name = "Clean Hugo Blog Theme"
license = "MIT"
licenselink = "https://github.com/souravbadami/clean-hugo-blog-theme/blob/master/LICENSE"
description = "Clean and lightweight Hugo theme with a focus on content."
homepage = "https://github.com/souravbadami/clean-hugo-blog-theme"
demosite = "https://souravbadami.com"
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive", "dark mode", "privacy"]
features = ["fast", "blog", "syntax highlighting", "dark mode"]
min_version = "0.41"

[author]
  name = "Sourav Badami"
  homepage = "https://souravbadami.com"
